name: Deployment

on:
  push:
    tags:
      - "*.*.*.*"

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Executing Remote SSH Commands Using Password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_TAILSCALE }}
          username: ${{ secrets.SSH_USERNAME}}
          password: ${{ secrets.SSH_PASSWORD}}
          port: 22
          command_timeout: 1337m
          script_stop: true
          script: |
            cd ${{ secrets.REPOSITORY_LOCATION }}
            git pull origin master --force
            docker compose -f docker-compose.production.yml stop
            docker compose -f docker-compose.production.yml build
            docker compose -f docker-compose.production.yml up -d
            docker compose -f docker-compose.production.yml run --rm django python manage.py migrate
            docker builder prune --force
