name: Deployment

on:
  push:
    tags:
      - "*.*.*.*"

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Extract Tag Name
        id: tag
        run: echo "name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.name }}
          release_name: ${{ steps.tag.outputs.name }}
          draft: false
          prerelease: false

      - name: Executing Remote SSH Commands Using Password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME}}
          password: ${{ secrets.SSH_PASSWORD}}
          port: 22
          command_timeout: 1337m
          script_stop: true
          script: |
            cd ${{ secrets.REPOSITORY_LOCATION }}
            git pull origin master --force
            docker compose -f docker-compose.production.yml stop
            docker compose -f docker-compose.production.yml build
            docker compose -f docker-compose.production.yml up -d
            docker compose -f docker-compose.production.yml run --rm django python manage.py migrate
            docker builder prune --force
